### ISSUE TITLE
openmq.py: mq_config not defined

### ISSUE THREAD

**Issue by martin3000** [tuya/tuya-iot-python-sdk#20]
I get the following exception:

> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/home/nuc/.homeassistant/deps/lib/python3.8/site-packages/tuya_iot/openmq.py", line 174, in run
>     time.sleep(self.mq_config.expire_time - 60)
> AttributeError: 'NoneType' object has no attribute 'expire_time'

**Comment by frenck** [comment]
This is a common issue, can we update/catch the error and display a proper error message or give a log that hints how to fix the issue?

**Comment by martin3000** [comment]
> [tuya/tuya-home-assistant#113](https://github.com/tuya/tuya-home-assistant/discussions/113) Check if "Device status notification" subscribed.

I have to buy that for $0. Do I need it if I don't have MQTT?
