### ISSUE TITLE
Feature request: add battery_low information

### ISSUE THREAD

**Issue by t0ny-peng** [tuya/tuya-iot-python-sdk#3]
Hi @tsutsuku. Thank for the effort of maintaining this repo. 

From what it states in the doc of [Tuya open API](https://developer.tuya.com/en/docs/cloud/device-management?id=K9g6rfntdz78a#title-8-Return%20example), the returned message seems to contain a field called `battery_low` indicating if the battery is low(obviously). But this field is missing in the [device information](https://github.com/tuya/tuya-iot-python-sdk/blob/master/tuya_iot/device.py#L39). Is the return message just for demo purpose? If not, it shouldn't be hard to add the missing part, right?

Thx.

**Comment by tsutsuku** [comment]
@t0ny-peng  
The battery_low is a dp code. Not all devices have this dp code. 
So It should not be in the normal device information.
Some device like a sensor, which may has this dp code,  can get it from the device's status dict.

data point (DP) : https://developer.tuya.com/en/docs/iot/terms?id=K914joq6tegj4
