### ISSUE TITLE
是否考虑实现 「获取 token」 API

### ISSUE THREAD

**Issue by wwj718** [tuya/tuya-iot-python-sdk#5]
[获取令牌 API](https://developer.tuya.com/cn/docs/cloud/6c1636a9bd?id=Ka7kjumkoa53v)

看起来这种 token 更为灵活

**Comment by tsutsuku** [comment]
这种token面向B端，现在还缺乏相关需求，所以还没考虑。

**Comment by wwj718** [comment]
好的 感谢回复
